# .github/workflows/docker-nodejs-template.yml

name: Reusable Node.js CI with Docker

on:
  workflow_call:
    inputs:
      DOCKER_IMAGE:
        description: 'Docker Image Name'
        required: true
        type: string
    secrets:
      DOCKER_USER:
        description: 'Docker Hub Username'
        required: true
      DOCKER_PASS:
        description: 'Docker Hub Password'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ inputs.docker-image-name }}
